apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ecom-dev
stringData:
  POSTGRES_USER: glowcare
  POSTGRES_PASSWORD: ChangeMe123!
  POSTGRES_DB: glowcare
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ecom-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          envFrom:
            - secretRef:
                name: postgres-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          emptyDir: {}   # مؤقت؛ لو عايز البيانات تفضل بعد إعادة تشغيل الـ pod، بدّلها بـ PVC
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ecom-dev
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
