global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "product-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["product-service:5001"]

  - job_name: "cart-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["cart-service:5002"]

  - job_name: "inventory-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["inventory-service:5003"]

  - job_name: "order-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["order-service:5004"]

  - job_name: "notification-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["notification-service:5005"]

  - job_name: "api-gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["api-gateway:8080"]
