apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: ecom-prod
data:
  PORT: "8080"
  PRODUCT_SERVICE_URL: "http://product-service.ecom-prod.svc.cluster.local"
  CART_SERVICE_URL: "http://cart-service.ecom-prod.svc.cluster.local"
  INVENTORY_SERVICE_URL: "http://inventory-service.ecom-prod.svc.cluster.local"
  ORDER_SERVICE_URL: "http://order-service.ecom-prod.svc.cluster.local"
  NOTIFICATION_SERVICE_URL: "http://notification-service.ecom-prod.svc.cluster.local"
